version: '2.1'
networks:
  app_net:
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.17.0/24
        gateway: 172.16.17.254

services:
  mysql:
#    image: mysql:5.7.36
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${DATA_PATH}/mysql_data:/var/lib/mysql"
      - "${DATA_PATH}/init.sql:/init.sql"
    restart: always
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    hostname: "${COMPOSE_PROJECT_NAME}_mysql"
#    hostname: mysql

#    logging:
#      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      app_net:


# docker run --name guacd -d guacamole/guacd
  guacd:
#    image: guacamole/guacd
    build:
      context: ./guacd
      dockerfile: Dockerfile

    container_name: "${COMPOSE_PROJECT_NAME}_guacd"
    hostname: "${COMPOSE_PROJECT_NAME}_guacd"
    volumes:
      - "${DATA_PATH}/record_session:/opt/record_session"
    restart: always
#    logging:
#      driver: none
    networks:
      app_net:

#docker run --name guacamole     --link guacd:guacd         -d -p 8081:8080 guacamole/guacamole
  guacamole:
#    image: guacamole/guacamole
    build:
      context: ./guacamole
      dockerfile: Dockerfile

    container_name: "${COMPOSE_PROJECT_NAME}_guacamole"
    hostname: "${COMPOSE_PROJECT_NAME}_guacamole"
    links:
      - guacd
    ports:
      -  "${HTTP_IP}:${HTTP_PORT}:8080"
    depends_on:
      - guacd

    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      GUACAMOLE_HOME: "/opt/GUACAMOLE_HOME"
      LDAP_HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_GROUP_BASE_DN: ${LDAP_GROUP_BASE_DN}
      LDAP_SEARCH_BIND_DN: ${LDAP_SEARCH_BIND_DN}
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USERNAME_ATTRIBUTE: ${LDAP_USERNAME_ATTRIBUTE}

# Required environment variables
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - "${DATA_PATH}/init.sql:/init.sql"
      - "${DATA_PATH}/GUACAMOLE_HOME:/opt/GUACAMOLE_HOME"
#    logging:
#      driver: none
    networks:
      app_net:
