version: '2.1'

services:

  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ${DATA_PATH}/nginx-le/etc/.htpasswd:/etc/nginx/.htpasswd
      - ${DATA_PATH}/nginx-le/etc/ssl:/etc/nginx/ssl
      - ${DATA_PATH}/nginx-le/etc/service-example.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"

    environment:
      - TZ=${TZ}
      - LETSENCRYPT=true
      - LE_EMAIL=${LE_EMAIL}
      - LE_FQDN=${LE_FQDN}

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${DATA_PATH}/mysql_data:/var/lib/mysql"
      - "${DATA_PATH}/init.sql:/init.sql"
    restart: always
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


# docker run --name guacd -d guacamole/guacd
  guacd:
    image: guacamole/guacd
    container_name: "${COMPOSE_PROJECT_NAME}_guacd"
    volumes:
      - "${DATA_PATH}/record_session:/opt/record_session"
    restart: always
    logging:
      driver: none

#docker run --name guacamole     --link guacd:guacd         -d -p 8081:8080 guacamole/guacamole
  guacamole:
    image: guacamole/guacamole
    container_name: "${COMPOSE_PROJECT_NAME}_guacamole"
    links:
      - guacd
    ports:
      -  "${HTTP_IP}:${HTTP_PORT}:8080"
    depends_on:
      - guacd

    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      GUACAMOLE_HOME: "/opt/GUACAMOLE_HOME"
      LDAP_HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_GROUP_BASE_DN: ${LDAP_GROUP_BASE_DN}
      LDAP_SEARCH_BIND_DN: ${LDAP_SEARCH_BIND_DN}
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USERNAME_ATTRIBUTE: ${LDAP_USERNAME_ATTRIBUTE}

# Required environment variables
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - "${DATA_PATH}/init.sql:/init.sql"
      - "${DATA_PATH}/GUACAMOLE_HOME:/opt/GUACAMOLE_HOME"
    logging:
      driver: none
